[package]
name = "rust-woff"
version = "0.0.2"
authors = ["Patrick Walton <pcwalton@mimiga.net>"]
edition="2015"

[lib]
name = "woff"
path = "lib.rs"

[[bin]]
name = "woffdec"
path = "woffdec.rs"

[[test]]
name = "basic"
path = "tests/basic.rs"

[dependencies]
byteorder = "1.4"
flate2 = "0.2"
